### ISSUE TITLE
Clicking the exe.

### ISSUE THREAD

**Issue by sutex** [TuTAH1/SteamVR-Toggle-for-Viveport#4]
Using the exe. I get this message 
Specified argument was out of the range of valid values. (Parameter 'There's no position 1 in string s[0]')

**Comment by TuTAH1** [comment]
Most likely, that's happens becouse my programm see empty string in `InstallLocation` parametr of `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 250820` of Registry.
I probably fixed that in the [new update](https://github.com/TuTAH1/SteamVR-OculusDash-Switcher/releases/tag/2.0.2), try it.
Can you also say the value of this parametr?

**Comment by sutex** [comment]
The update worked. Icon is in the system tray.

**Can you also say the value of this parametr?** 
![2023-04-23 15_49_13-Registry Editor](https://user-images.githubusercontent.com/10361359/233823324-47b40b93-49b5-49c1-bd4f-05d2b3d96ab1.png)
